package Recursos;

public class MovesValues {
    
    public char convertToChar(int number){
        switch(number){
            case 0:
                return 'a';
            case 10:
                return 'b';
            case 20:
                return 'c';
            case 30:
                return 'd';    
            case 40:
                return 'e';
            case 50:
                return 'f';
            case 60:
                return 'g';
            case 70:
                return 'h';
            case 80:
                return 'i';
            case 90:
                return 'j';
            case 100:
                return 'k';
            case 110:
                return 'l';
            case 120:
                return 'm';
            case 130:
                return 'n';
            case 140:
                return 'o';
            case 150:
                return 'p';
            case 160:
                return 'q';
            case 170:
                return 'r';
            case 180:
                return 's';
            case 190:
                return 't';
            case 200:
                return 'u';
            case 210:
                return 'v';
            case 220:
                return 'x';
            case 230:
                return 'y';
            case 240:
                return 'z';
            case 250:
                return 'A';
            case 260:
                return 'B';
            case 270:
                return 'C';
            case 280:
                return 'D';
            case 290:
                return 'E';
            case 300:
                return 'F';
            case 310:
                return 'G';
            case 320:
                return 'H';
            case 330:
                return 'I';
            case 340:
                return 'J';
            case 350:
                return 'K';
            case 360:
                return 'L';
            default:
                return '>';
        }
    }
    public int convertToInt(char letter){
        switch(letter){
            case 'a':
                return 0;
            case 'b':
                return 10;
            case 'c':
                return 20;
            case 'd':
                return 30;    
            case 'e':
                return 40;
            case 'f':
                return 50;
            case 'g':
                return 60;
            case 'h':
                return 70;
            case 'i':
                return 80;
            case 'j':
                return 90;
            case 'k':
                return 100;
            case 'l':
                return 110;
            case 'm':
                return 120;
            case 'n':
                return 130;
            case 'o':
                return 140;
            case 'p':
                return 150;
            case 'q':
                return 160;
            case 'r':
                return 170;
            case 's':
                return 180;
            case 't':
                return 190;
            case 'u':
                return 200;
            case 'v':
                return 210;
            case 'x':
                return 220;
            case 'y':
                return 230;
            case 'z':
                return 240;
            case 'A':
                return 250;
            case 'B':
                return 260;
            case 'C':
                return 270;
            case 'D':
                return 280;
            case 'E':
                return 290;
            case 'F':
                return 300;
            case 'G':
                return 310;
            case 'H':
                return 320;
            case 'I':
                return 330;
            case 'J':
                return 340;
            case 'K':
                return 350;
            case 'L':
                return 360;
            default:
                return -1;
        }
    }
}
